### ISSUE TITLE
-Dport commandline argument does not work in Azure Container App

### ISSUE THREAD

**Issue by MoonBow-1** [teragrep/rlp_07#18]
**Describe the bug**

 I would like to change the port from the default **1601** with command `-Dport=1234` in an Azure Container App. Application ignores the argument, and tries to start with the default port.
**Expected behavior**

 Application starts with the port specified in the argument
**How to reproduce**

1. Create a container app
2. Use the container image for RLP_07
3. Add argument `-Dport=1234` to the app
4. Finalize creation
5. Wait and see that the pod does not start (Currently status is "Degraded")

**Screenshots**

 
**Software version**
 rlp_07/app:1.1.0
 
**Container (please complete the following information if relevant):**
 - CPU cores: 0.5
 - Memory: 1 Gi
 
**Additional context**

Container logs:
![image](https://github.com/user-attachments/assets/3ac2b4c1-06d7-40cd-8622-186dd8787bcc)

YAML file to import RLP_07 with
```yml
apiVersion: v1
kind: Pod
metadata:
  name:  rlp-07
spec:
  containers:
  - name:  rlp-07
    image: ghcr.io/teragrep/rlp_07/app:1.1.0
```
